name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf 
        with:
          ruby-version: 3.2.2 

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v18.17.0.
          
      - name: Deploy to Windows EC2
        run: |
          $ec2InstanceIP = "13.51.238.91"
          $ec2Username = "Administrator"
          $privateKeyPath = "C:\Users\PC\Downloads\resto-review.pem"
          
          Enter-PSSession -ComputerName $ec2InstanceIP -Credential $ec2Username -SSHTransport -SSHPrivateKey $privateKeyPath

          cd C:\Users\PC\devopsproject

          gem install bundler
          bundle install

          
          rails db:create
          rails db:migrate

          rails assets:precompile

          rails server -d

          Exit-PSSession

