name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf 
        with:
          ruby-version: 3.2.2 

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rake
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.51.238.91
          username: Administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the private key as a secret in your repository

        # Add any commands to perform deployment tasks on your EC2 instance here

